apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: nimesh-ns-photo
spec:
  addresses:
  - 10.0.0.1-10.0.0.20

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: nimesh-ns-photo