apiVersion: v1
kind: Secret
metadata:
  name: photostudio-secret
  namespace: nimesh-ns-photo
type: Opaque
stringData:
  MONGODB_AUTH_URI: mongodb://mongodb-service:27017/artgallery
  MONGODB_FEEDBACK_URI: mongodb://mongodb-service:27017/artgallery
  MONGO_URI: mongodb://mongodb-service:27017
